In [1]:
!pip3 install numpy

In [2]:
import numpy as np

In [3]:
l1 = [1, 2, 3]
x = np.array(l1, np.int16)

In [4]:
x = np.array(l1, dtype = np.int16)

In [8]:
x

array([1, 2, 3], dtype=int16)

In [6]:
type(x)

numpy.ndarray

In [7]:
x[0]

np.int16(1)

In [9]:
x[2]

np.int16(3)

In [10]:
x[1]

np.int16(2)

In [11]:
x[-1]

np.int16(3)

In [12]:
x[4]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [13]:
x1 = np.array([[1, 2, 3],
              [4, 5, 6]],
             np.int8)
x1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

In [14]:
x1[0, 0]

np.int8(1)

In [15]:
x1[0, 1]

np.int8(2)

In [16]:
x1[0, 2]

np.int8(3)

In [17]:
x1[:, 0]

array([1, 4], dtype=int8)

In [18]:
x1[:, 1]

array([2, 5], dtype=int8)

In [19]:
x1[:, 2]

array([3, 6], dtype=int8)

In [20]:
x1[0, :]

array([1, 2, 3], dtype=int8)

In [22]:
x1[1, :]

array([4, 5, 6], dtype=int8)

In [23]:
x1[2, :]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [21]:
x1 = np.array([[[1, 2, 3], [4, 5, 6]],
               [[0, -1, -2], [-3, -4, -5]]],
              np.int8)
x1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0, -1, -2],
        [-3, -4, -5]]], dtype=int8)

In [22]:
x1 [ 0, 0, 0]

np.int8(1)

In [23]:
x1 [ -1, 0, 0]

np.int8(0)

In [24]:
x1 [ -1, -1, -1]

np.int8(-5)

# Properties of Ndarrays

In [25]:
x2 = np.array([[[1, 2, 3], [4, 5, 6]],
               [[0, -1, -2], [-3, -4, -5]],
               [[0, 0, 1], [-1, -3, 4]]],
              np.int16)
x2

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0, -1, -2],
        [-3, -4, -5]],

       [[ 0,  0,  1],
        [-1, -3,  4]]], dtype=int16)

In [26]:
x2.ndim

3

In [27]:
x2.shape

(3, 2, 3)

In [28]:
x2.dtype

dtype('int16')

In [29]:
x2.size

18

In [30]:
x2.nbytes

36

In [31]:
x2.T

array([[[ 1,  0,  0],
        [ 4, -3, -1]],

       [[ 2, -1,  0],
        [ 5, -4, -3]],

       [[ 3, -2,  1],
        [ 6, -5,  4]]], dtype=int16)

# NumPy constants

In [32]:
np.inf

inf

In [33]:
np.NAN

AttributeError: module 'numpy' has no attribute 'NAN'

In [37]:
-np.inf

-inf

In [38]:
-0.0

-0.0

In [39]:
0.0

0.0

In [40]:
np.e

2.718281828459045

In [41]:
np.pi

3.141592653589793

In [42]:
np.euler_gamma

0.5772156649015329

# Slicing

In [43]:
a1 = np.array([1, 2, 3, 4, 5, 6, 7])

In [44]:
a1.dtype

dtype('int64')

In [45]:
a1.nbytes

56

In [46]:
a1[1:5]

array([2, 3, 4, 5])

In [47]:
a1[3:]

array([4, 5, 6, 7])

In [48]:
a1[:3]

array([1, 2, 3])

In [50]:
a1[-4:-1]

array([4, 5, 6])

In [51]:
a1[1:6:2]

array([2, 4, 6])

In [52]:
a5 = [0,5,3,6,1,3,5,7,8,9,5,3,6,6,8,3,2,3,5]

In [53]:
a5[5]

3

In [54]:
a5[1:5]

[5, 3, 6, 1]

In [55]:
a5[:1]

[0]

In [57]:
a5[1:4:7]

[5]

In [58]:
a5[7:]

[7, 8, 9, 5, 3, 6, 6, 8, 3, 2, 3, 5]

In [59]:
a5[8:11]

[8, 9, 5]