In [1]:
!python -m pip install --upgrade pip

In [2]:
!pip3 install opencv-python

   ---------------------------------------- 0.0/38.8 MB ? eta -:--:--
   - -------------------------------------- 1.6/38.8 MB 10.5 MB/s eta 0:00:04
   ---- ----------------------------------- 4.2/38.8 MB 11.5 MB/s eta 0:00:04
   ----- ---------------------------------- 5.8/38.8 MB 10.4 MB/s eta 0:00:04
   -------- ------------------------------- 7.9/38.8 MB 9.7 MB/s eta 0:00:04
   --------- ------------------------------ 8.9/38.8 MB 8.7 MB/s eta 0:00:04
   ----------- ---------------------------- 10.7/38.8 MB 8.7 MB/s eta 0:00:04
   ------------- -------------------------- 12.8/38.8 MB 8.8 MB/s eta 0:00:03
   --------------- ------------------------ 14.7/38.8 MB 9.0 MB/s eta 0:00:03
   --------------- ------------------------ 15.5/38.8 MB 8.2 MB/s eta 0:00:03
   ---------------- ----------------------- 16.3/38.8 MB 7.9 MB/s eta 0:00:03
   ----------------- ---------------------- 17.3/38.8 MB 7.5 MB/s eta 0:00:03
   ------------------ --------------------- 17.8/38.8 MB 7.2 MB/s eta 0:00

In [3]:
!python -m pip install --upgrade opencv-python

In [4]:
import cv2

In [5]:
print(cv2.__version__)

4.10.0


In [6]:
imgpath = 'C:/Dataset/4.2.03.tiff'
#imgpath = '/home/pi/Dataset/4.2.03.tiff'
img = cv2.imread(imgpath)

In [7]:
type(img)

numpy.ndarray

In [ ]:
cv2.imshow('Mandrill', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.namedWindow('Mandrill', cv2.WINDOW_AUTOSIZE)
cv2.imshow('Mandrill', img)
cv2.waitKey(0)
cv2.destroyWindow('Mandrill')

error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-sn_xpupm\opencv\modules\highgui\src\window_w32.cpp:1246: error: (-27:Null pointer) NULL window: 'Mandrill' in function 'cvDestroyWindow'


In [ ]:
outpath = 'C:/Dataset/output.jpg'
cv2.imwrite(outpath, img)

NameError: name 'cv2' is not defined

In [ ]:
img = cv2.imread(imgpath, 0)
cv2.imshow('Mandrill', img)
cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'cv2' is not defined

In [8]:
import numpy as np
img1 = np.zeros((512, 512, 3), np.uint8)

In [9]:
cv2.line(img1, (0, 99), (99, 0), (255, 0, 0), 2)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [10]:
cv2.rectangle(img1, (100, 60), (200, 170), (0, 255, 0), 2)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [11]:
cv2.circle(img1, (60, 60), 50, (0, 0, 255), -1)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [12]:
cv2.ellipse(img1, (100, 200), (50, 20), 0, 0, 360, (127, 127, 127), -1)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [13]:
points = np.array([[80, 2], [125, 0],
                  [170, 0], [230, 5],
                  [30, 50]], np.int32)
points = points.reshape((-1, 1, 2))
cv2.polylines(img1, [points], True, (0, 255, 255))
text1 = 'Test Text'
cv2.putText(img1, text1, (100, 100), 
            cv2.FONT_HERSHEY_SIMPLEX,
           5, (255, 255, 0))

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [14]:
cv2.imshow('Shapes', img1)
cv2.waitKey(0)
cv2.destroyAllWindows()